# -*- coding: utf-8 -*-
"""Perpose_of_action.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_y_jQmns55lSS1hVqPRHchIVhWMNNlY
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import csv
import numpy as np
from scipy.spatial import distance

"""**移動手段の分析**
- 考えられる移動方法は徒歩、走り、自転車、電車、車の5種類
- 判断材料はgps,歩数計,Placeの3種類
"""

df_taiou=pd.read_csv('/content/drive/My Drive/Colab Notebooks/mirai_souzou/keisoku_data.csv', encoding='utf-8')
df_taiou.head()

df_taiou.shape

yn=np.array([
      ["徒歩"],
      ["走り"],
      ["自転車"],
      ["電車"],
      ["車両"],
      ])
yn.shape

"""## ケース1「電車内で別の車両に移動中(車両で移動中、歩き」"""

df_zissoku1=pd.read_csv('/content/drive/My Drive/Colab Notebooks/mirai_souzou/zissookuchi.csv', encoding='utf-8')
df_zissoku1
# 電車内で別の車両に移動中(車両で移動中、歩き)

df_zissoku1.shape

y = np.dot(df_taiou, df_zissoku1) # 
y

c = np.concatenate((y,yn), axis = 1)
c

"""## ケース2「ランニング中」"""

df_zissoku2=pd.read_csv('/content/drive/My Drive/Colab Notebooks/mirai_souzou/zissookuchi1.csv', encoding='utf-8')
df_zissoku2

df_zissoku1.shape

y1 = np.dot(df_taiou, df_zissoku2) # 
y1

c = np.concatenate((y1,yn), axis = 1)
c

